<html lang="en">

<head>
    <title>Code</title>
    <style>
        pre {
          border: groove;
        background-color: lightgrey;
 }

        span {
            color: green;
        } </style>
    <link rel="stylesheet"
          href="https://cdn.jsdelivr.net/gh/highlightjs/cdn-release@11.4.0/build/styles/dark.min.css">
    <script src="https://cdn.jsdelivr.net/gh/highlightjs/cdn-release@11.4.0/build/highlight.js"></script>
    <script>hljs.highlightAll();</script>

</head>
<body>

<#setting locale="en_US" >
<span id="load_date"> ${date} </span>
<pre><code>${code}</code></pre>

</body>
</html>